[tool.poetry]
name = "information_robot"
version = "0.1.0"
description = "information robot"
authors = ["Iydon Liang <liangiydon@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8.*"
graia-application-mirai = "^0.19.1"
graia-scheduler = "^0.0.4"
PyYAML = "^5.4.1"
tinydb = "^4.5.0"
fuzzywuzzy = {extras = ["speedup"], version = "^0.18.0"}

[tool.poetry.dev-dependencies]
ipython = "^7.25.0"
pyperclip = "^1.8.2"
prompt-toolkit = "^3.0.19"
Pygments = "^2.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
